### ISSUE TITLE
It's impossible to use example's name in generated URL

### ISSUE THREAD

**Issue by huston007** [kisenka/webpack-docs-plugin#2]
`docs/components/<example-file-name>/<example-file-name>.js/examples/example-0.html` is not so useful and stable URL. It's better to be able to use real example name somewhere here

**Comment by kisenka** [comment]
@huston007 @princed 
Shipped with 1.0.10-alpha. And you don't need to create example name converter. [url-slug](https://www.npmjs.com/package/url-slug) will be used to replace `[example-name]` placeholder.

**Comment by princed** [comment]
Great, thanks!
